### ISSUE TITLE
[Basics - Architecture]: Introduction

### ISSUE THREAD

**Issue by rmdias** [angular/angular-pt#21]
Translate topic -> Introduction from https://angular.io/docs/ts/latest/guide/architecture.html

**Comment by Lucasktrindade** [comment]
Can i translate this topic?

**Comment by rmdias** [comment]
sure @Lucasktrindade  :)

**Comment by cironunes** [comment]
@Lucasktrindade we're focusing on the glossary first. Would you be interested in taking one of the open issues related?

**Comment by Lucasktrindade** [comment]
Yes, which one?
